const ANDROID_LOCALHOST = '10.0.2.2';
const REOMTE_SERVER = 'zenbaei.ddns.net';
const SERVER_PORT = '3500';
const SERVER = REOMTE_SERVER;
export const APP_NAME = 'azbakia';
export const APP_API = `https://${SERVER}:${SERVER_PORT}/api/${APP_NAME}`;
export const EMAIL_API = `https://${SERVER}:${SERVER_PORT}/api/email`;
export const STATIC_FILES_URL = `https://${SERVER}:${SERVER_PORT}/static`;
export const ACTIVATION_API = `${APP_API}/activate`;
export const IP_DATA_API =
  'https://api.ipdata.co/?api-key=70db9e3404500cbd042097a219048e0fd28f3144ac0091cde2fd3991';
